// combinatorial-catalog.js — V3 experimental content supply.
//
// This catalogue is intentionally isolated from the production V2 registry.
// Each frame contains two semantically compatible bilingual slot banks.
// The materializer expands every frame deterministically as a Cartesian product.
// 36 frames × 8 × 8 = 2,304 candidate realizations.
//
// The first experiment optimizes for breadth of common everyday English while
// keeping every surface traceable to curated slot text. Nothing here is treated
// as learner evidence or silently promoted into production.

const s = (id, en, pt) => Object.freeze({ id, en, pt })
const frame = (focus_id, stage, category, template_en, template_pt, a, b) =>
  Object.freeze({
    focus_id, stage, category, template_en, template_pt,
    slots: Object.freeze({ a: Object.freeze(a), b: Object.freeze(b) }),
  })

const PAST_TIMES = Object.freeze([
  s('yesterday', 'yesterday', 'ontem'),
  s('last_night', 'last night', 'ontem à noite'),
  s('last_week', 'last week', 'na semana passada'),
  s('on_monday', 'on Monday', 'na segunda-feira'),
  s('this_morning', 'this morning', 'hoje de manhã'),
  s('two_days_ago', 'two days ago', 'há dois dias'),
  s('after_work', 'after work', 'depois do trabalho'),
  s('before_dinner', 'before dinner', 'antes do jantar'),
])

const FUTURE_TIMES = Object.freeze([
  s('tomorrow', 'tomorrow', 'amanhã'),
  s('tonight', 'tonight', 'hoje à noite'),
  s('this_weekend', 'this weekend', 'neste fim de semana'),
  s('next_week', 'next week', 'na próxima semana'),
  s('after_lunch', 'after lunch', 'depois do almoço'),
  s('before_dinner', 'before dinner', 'antes do jantar'),
  s('later_today', 'later today', 'mais tarde hoje'),
  s('on_friday', 'on Friday', 'na sexta-feira'),
])

const ROUTINE_CONTEXTS = Object.freeze([
  s('every_day', 'every day', 'todos os dias'),
  s('on_weekdays', 'on weekdays', 'nos dias de semana'),
  s('on_weekends', 'on weekends', 'nos fins de semana'),
  s('before_work', 'before work', 'antes do trabalho'),
  s('after_dinner', 'after dinner', 'depois do jantar'),
  s('in_the_morning', 'in the morning', 'de manhã'),
  s('at_night', 'at night', 'à noite'),
  s('when_time', 'when you have time', 'quando você tem tempo'),
])

const GENERIC_REQUEST_CONTEXTS = Object.freeze([
  s('please', 'please', 'por favor'),
  s('if_possible', 'if possible', 'se possível'),
  s('for_me', 'for me', 'para mim'),
  s('right_now', 'right now', 'agora'),
  s('before_leave', 'before we leave', 'antes de irmos embora'),
  s('when_moment', 'when you have a moment', 'quando você tiver um momento'),
  s('this_morning', 'this morning', 'hoje de manhã'),
  s('asap', 'as soon as possible', 'assim que possível'),
])

export const COMBINATORIAL_FRAMES_V3 = Object.freeze([
  frame(
    'v3.be.location', 'A1', 'be',
    '{{a}} {{b}}.', '{{a}} {{b}}.',
    [
      s('i_am', 'I am', 'Eu estou'),
      s('you_are', 'You are', 'Você está'),
      s('he_is', 'He is', 'Ele está'),
      s('she_is', 'She is', 'Ela está'),
      s('we_are', 'We are', 'Nós estamos'),
      s('they_are', 'They are', 'Eles estão'),
      s('brother_is', 'My brother is', 'Meu irmão está'),
      s('friends_are', 'Our friends are', 'Nossos amigos estão'),
    ],
    [
      s('at_home', 'at home', 'em casa'),
      s('at_work', 'at work', 'no trabalho'),
      s('at_school', 'at school', 'na escola'),
      s('at_station', 'at the station', 'na estação'),
      s('in_kitchen', 'in the kitchen', 'na cozinha'),
      s('in_car', 'in the car', 'no carro'),
      s('near_entrance', 'near the entrance', 'perto da entrada'),
      s('outside', 'outside', 'do lado de fora'),
    ],
  ),
  frame(
    'v3.have.possession', 'A1', 'have',
    '{{a}} {{b}}.', '{{a}} {{b}}.',
    [
      s('i_have', 'I have', 'Eu tenho'),
      s('you_have', 'You have', 'Você tem'),
      s('he_has', 'He has', 'Ele tem'),
      s('she_has', 'She has', 'Ela tem'),
      s('we_have', 'We have', 'Nós temos'),
      s('they_have', 'They have', 'Eles têm'),
      s('friend_has', 'My friend has', 'Meu amigo tem'),
      s('team_has', 'Our team has', 'Nossa equipe tem'),
    ],
    [
      s('question', 'a question', 'uma pergunta'),
      s('problem', 'a problem', 'um problema'),
      s('time', 'enough time', 'tempo suficiente'),
      s('reservation', 'a reservation', 'uma reserva'),
      s('idea', 'an idea', 'uma ideia'),
      s('key', 'the key', 'a chave'),
      s('tickets', 'two tickets', 'dois ingressos'),
      s('meeting', 'a meeting today', 'uma reunião hoje'),
    ],
  ),
  frame(
    'v3.want.to_action', 'A1', 'modal_intent',
    '{{a}} {{b}}.', '{{a}} {{b}}.',
    [
      s('i_want', 'I want to', 'Eu quero'),
      s('you_want', 'You want to', 'Você quer'),
      s('he_wants', 'He wants to', 'Ele quer'),
      s('she_wants', 'She wants to', 'Ela quer'),
      s('we_want', 'We want to', 'Nós queremos'),
      s('they_want', 'They want to', 'Eles querem'),
      s('friend_wants', 'My friend wants to', 'Meu amigo quer'),
      s('parents_want', 'My parents want to', 'Meus pais querem'),
    ],
    [
      s('go_home', 'go home', 'ir para casa'),
      s('eat_now', 'eat now', 'comer agora'),
      s('learn_english', 'learn English', 'aprender inglês'),
      s('buy_ticket', 'buy a ticket', 'comprar um ingresso'),
      s('call_mom', 'call my mother', 'ligar para minha mãe'),
      s('leave_early', 'leave early', 'sair cedo'),
      s('see_menu', 'see the menu', 'ver o cardápio'),
      s('talk_manager', 'talk to the manager', 'falar com o gerente'),
    ],
  ),
  frame(
    'v3.need.to_action', 'A1', 'modal_need',
    '{{a}} {{b}}.', '{{a}} {{b}}.',
    [
      s('i_need', 'I need to', 'Eu preciso'),
      s('you_need', 'You need to', 'Você precisa'),
      s('he_needs', 'He needs to', 'Ele precisa'),
      s('she_needs', 'She needs to', 'Ela precisa'),
      s('we_need', 'We need to', 'Nós precisamos'),
      s('they_need', 'They need to', 'Eles precisam'),
      s('friend_needs', 'My friend needs to', 'Meu amigo precisa'),
      s('team_needs', 'Our team needs to', 'Nossa equipe precisa'),
    ],
    [
      s('leave', 'leave now', 'sair agora'),
      s('finish', 'finish this today', 'terminar isto hoje'),
      s('check', 'check the address', 'verificar o endereço'),
      s('charge', 'charge the phone', 'carregar o celular'),
      s('book', 'book a room', 'reservar um quarto'),
      s('send', 'send an email', 'enviar um e-mail'),
      s('rest', 'get some rest', 'descansar um pouco'),
      s('decide', 'make a decision', 'tomar uma decisão'),
    ],
  ),
  frame(
    'v3.can.ability', 'A1', 'modal_can',
    '{{a}} {{b}}.', '{{a}} {{b}}.',
    [
      s('i_can', 'I can', 'Eu posso'),
      s('you_can', 'You can', 'Você pode'),
      s('he_can', 'He can', 'Ele pode'),
      s('she_can', 'She can', 'Ela pode'),
      s('we_can', 'We can', 'Nós podemos'),
      s('they_can', 'They can', 'Eles podem'),
      s('friend_can', 'My friend can', 'Meu amigo pode'),
      s('team_can', 'Our team can', 'Nossa equipe pode'),
    ],
    [
      s('drive', 'drive at night', 'dirigir à noite'),
      s('cook', 'cook dinner', 'preparar o jantar'),
      s('speak', 'speak English', 'falar inglês'),
      s('help', 'help with that', 'ajudar com isso'),
      s('come', 'come tomorrow', 'vir amanhã'),
      s('pay', 'pay by card', 'pagar com cartão'),
      s('wait', 'wait a little longer', 'esperar mais um pouco'),
      s('start', 'start now', 'começar agora'),
    ],
  ),
  frame(
    'v3.should.advice', 'A2', 'modal_advice',
    'You should {{a}} {{b}}.', 'Você deveria {{a}} {{b}}.',
    [
      s('bring_jacket', 'bring a jacket', 'levar uma jaqueta'),
      s('save_copy', 'save a copy', 'salvar uma cópia'),
      s('check_address', 'check the address', 'verificar o endereço'),
      s('charge_phone', 'charge your phone', 'carregar seu celular'),
      s('leave_early', 'leave early', 'sair cedo'),
      s('ask_help', 'ask for help', 'pedir ajuda'),
      s('read_instructions', 'read the instructions', 'ler as instruções'),
      s('call_ahead', 'call ahead', 'ligar antes'),
    ],
    [
      s('today', 'today', 'hoje'),
      s('first', 'first', 'primeiro'),
      s('before_go', 'before you go', 'antes de ir'),
      s('if_possible', 'if possible', 'se possível'),
      s('before_tomorrow', 'before tomorrow', 'antes de amanhã'),
      s('before_trip', 'before the trip', 'antes da viagem'),
      s('while_time', 'while you still have time', 'enquanto você ainda tem tempo'),
      s('before_busy', 'before it gets busy', 'antes de ficar cheio'),
    ],
  ),
  frame(
    'v3.have_to.obligation', 'A2', 'modal_obligation',
    'I have to {{a}} {{b}}.', 'Eu tenho que {{a}} {{b}}.',
    [
      s('work', 'work', 'trabalhar'),
      s('study', 'study', 'estudar'),
      s('leave', 'leave', 'sair'),
      s('call', 'call the client', 'ligar para o cliente'),
      s('shop', 'buy groceries', 'fazer compras'),
      s('clean', 'clean the apartment', 'limpar o apartamento'),
      s('finish', 'finish the report', 'terminar o relatório'),
      s('pay', 'pay the bill', 'pagar a conta'),
    ],
    FUTURE_TIMES,
  ),
  frame(
    'v3.simple_present.frequency', 'A1', 'simple_present',
    'I {{a}} {{b}}.', 'Eu {{a}} {{b}}.',
    [
      s('always', 'always', 'sempre'),
      s('usually', 'usually', 'geralmente'),
      s('often', 'often', 'frequentemente'),
      s('sometimes', 'sometimes', 'às vezes'),
      s('normally', 'normally', 'normalmente'),
      s('generally', 'generally', 'em geral'),
      s('rarely', 'rarely', 'raramente'),
      s('hardly_ever', 'hardly ever', 'quase nunca'),
    ],
    [
      s('check_email', 'check my email', 'verifico meu e-mail'),
      s('cook_home', 'cook at home', 'cozinho em casa'),
      s('take_train', 'take the train', 'pego o trem'),
      s('walk', 'go for a walk', 'saio para caminhar'),
      s('watch_tv', 'watch TV', 'assisto TV'),
      s('eat_out', 'eat out', 'como fora'),
      s('start_eight', 'start work at eight', 'começo a trabalhar às oito'),
      s('plan_week', 'plan my week on Sunday', 'planejo minha semana no domingo'),
    ],
  ),
  frame(
    'v3.simple_present.question', 'A1', 'questions',
    'Do you {{a}} {{b}}?', 'Você {{a}} {{b}}?',
    [
      s('drink_coffee', 'drink coffee', 'toma café'),
      s('work_home', 'work from home', 'trabalha de casa'),
      s('exercise', 'exercise', 'faz exercício'),
      s('cook', 'cook', 'cozinha'),
      s('read', 'read', 'lê'),
      s('drive', 'drive', 'dirige'),
      s('study_english', 'study English', 'estuda inglês'),
      s('call_family', 'call your family', 'liga para sua família'),
    ],
    ROUTINE_CONTEXTS,
  ),
  frame(
    'v3.simple_present.negative', 'A1', 'negation',
    'I do not {{a}} {{b}}.', 'Eu não {{a}} {{b}}.',
    [
      s('drink_coffee', 'drink coffee', 'tomo café'),
      s('drive', 'drive', 'dirijo'),
      s('eat_meat', 'eat meat', 'como carne'),
      s('work_late', 'work late', 'trabalho até tarde'),
      s('watch_tv', 'watch TV', 'assisto TV'),
      s('shop_online', 'shop online', 'compro pela internet'),
      s('use_car', 'use the car', 'uso o carro'),
      s('check_messages', 'check messages', 'vejo mensagens'),
    ],
    ROUTINE_CONTEXTS,
  ),
  frame(
    'v3.present_continuous.now', 'A1-A2', 'present_continuous',
    'I am {{a}} {{b}}.', 'Eu estou {{a}} {{b}}.',
    [
      s('working', 'working', 'trabalhando'),
      s('studying', 'studying', 'estudando'),
      s('cooking', 'cooking', 'cozinhando'),
      s('waiting', 'waiting', 'esperando'),
      s('driving', 'driving', 'dirigindo'),
      s('reading', 'reading', 'lendo'),
      s('packing', 'packing', 'arrumando as malas'),
      s('cleaning', 'cleaning', 'limpando'),
    ],
    [
      s('now', 'right now', 'agora'),
      s('moment', 'at the moment', 'neste momento'),
      s('today', 'today', 'hoje'),
      s('home', 'at home', 'em casa'),
      s('office', 'at the office', 'no escritório'),
      s('brother', 'with my brother', 'com meu irmão'),
      s('lunch', 'before lunch', 'antes do almoço'),
      s('evening', 'this evening', 'hoje à noite'),
    ],
  ),
  frame(
    'v3.present_continuous.question', 'A1-A2', 'questions',
    'Are you {{a}} {{b}}?', 'Você está {{a}} {{b}}?',
    [
      s('working', 'working', 'trabalhando'),
      s('studying', 'studying', 'estudando'),
      s('cooking', 'cooking', 'cozinhando'),
      s('waiting', 'waiting', 'esperando'),
      s('driving', 'driving', 'dirigindo'),
      s('reading', 'reading', 'lendo'),
      s('packing', 'packing', 'arrumando as malas'),
      s('cleaning', 'cleaning', 'limpando'),
    ],
    [
      s('now', 'right now', 'agora'),
      s('moment', 'at the moment', 'neste momento'),
      s('today', 'today', 'hoje'),
      s('home', 'at home', 'em casa'),
      s('office', 'at the office', 'no escritório'),
      s('alone', 'alone', 'sozinho'),
      s('lunch', 'before lunch', 'antes do almoço'),
      s('evening', 'this evening', 'hoje à noite'),
    ],
  ),
  frame(
    'v3.simple_past.affirmative', 'A2', 'simple_past',
    'I {{a}} {{b}}.', 'Eu {{a}} {{b}}.',
    [
      s('worked', 'worked from home', 'trabalhei de casa'),
      s('called', 'called my mother', 'liguei para minha mãe'),
      s('bought', 'bought groceries', 'fiz compras'),
      s('finished', 'finished the report', 'terminei o relatório'),
      s('visited', 'visited a friend', 'visitei um amigo'),
      s('watched', 'watched a movie', 'assisti a um filme'),
      s('cleaned', 'cleaned the apartment', 'limpei o apartamento'),
      s('cooked', 'cooked dinner', 'preparei o jantar'),
    ],
    PAST_TIMES,
  ),
  frame(
    'v3.simple_past.question', 'A2', 'questions',
    'Did you {{a}} {{b}}?', 'Você {{a}} {{b}}?',
    [
      s('work', 'work from home', 'trabalhou de casa'),
      s('call', 'call your mother', 'ligou para sua mãe'),
      s('buy', 'buy groceries', 'fez compras'),
      s('finish', 'finish the report', 'terminou o relatório'),
      s('visit', 'visit a friend', 'visitou um amigo'),
      s('watch', 'watch a movie', 'assistiu a um filme'),
      s('clean', 'clean the apartment', 'limpou o apartamento'),
      s('cook', 'cook dinner', 'preparou o jantar'),
    ],
    PAST_TIMES,
  ),
  frame(
    'v3.simple_past.negative', 'A2', 'negation',
    'I did not {{a}} {{b}}.', 'Eu não {{a}} {{b}}.',
    [
      s('work', 'work from home', 'trabalhei de casa'),
      s('call', 'call anyone', 'liguei para ninguém'),
      s('buy', 'buy anything', 'comprei nada'),
      s('finish', 'finish the report', 'terminei o relatório'),
      s('visit', 'visit anyone', 'visitei ninguém'),
      s('watch', 'watch TV', 'assisti TV'),
      s('drive', 'drive', 'dirigi'),
      s('cook', 'cook dinner', 'preparei o jantar'),
    ],
    PAST_TIMES,
  ),
  frame(
    'v3.future.going_to', 'A2', 'future',
    'I am going to {{a}} {{b}}.', 'Eu vou {{a}} {{b}}.',
    [
      s('work', 'work from home', 'trabalhar de casa'),
      s('call', 'call the client', 'ligar para o cliente'),
      s('buy', 'buy groceries', 'fazer compras'),
      s('finish', 'finish the report', 'terminar o relatório'),
      s('visit', 'visit my parents', 'visitar meus pais'),
      s('cook', 'cook dinner', 'preparar o jantar'),
      s('study', 'study English', 'estudar inglês'),
      s('rest', 'get some rest', 'descansar um pouco'),
    ],
    FUTURE_TIMES,
  ),
  frame(
    'v3.future.will', 'A2', 'future',
    'I will {{a}} {{b}}.', 'Eu vou {{a}} {{b}}.',
    [
      s('call', 'call you', 'ligar para você'),
      s('send', 'send the file', 'enviar o arquivo'),
      s('check', 'check the schedule', 'verificar o horário'),
      s('help', 'help with that', 'ajudar com isso'),
      s('decide', 'decide', 'decidir'),
      s('finish', 'finish this', 'terminar isto'),
      s('return', 'come back', 'voltar'),
      s('confirm', 'confirm the reservation', 'confirmar a reserva'),
    ],
    FUTURE_TIMES,
  ),
  frame(
    'v3.future.question', 'A2', 'questions',
    'Are you going to {{a}} {{b}}?', 'Você vai {{a}} {{b}}?',
    [
      s('work', 'work', 'trabalhar'),
      s('travel', 'travel', 'viajar'),
      s('cook', 'cook', 'cozinhar'),
      s('study', 'study', 'estudar'),
      s('shop', 'go shopping', 'fazer compras'),
      s('drive', 'drive', 'dirigir'),
      s('visit', 'visit your family', 'visitar sua família'),
      s('rest', 'rest', 'descansar'),
    ],
    FUTURE_TIMES,
  ),
  frame(
    'v3.there_is.singular', 'A1', 'existence',
    'There is {{a}} {{b}}.', 'Tem {{a}} {{b}}.',
    [
      s('cafe', 'a café', 'um café'),
      s('bank', 'a bank', 'um banco'),
      s('bathroom', 'a bathroom', 'um banheiro'),
      s('problem', 'a problem', 'um problema'),
      s('meeting', 'a meeting', 'uma reunião'),
      s('bus', 'a bus', 'um ônibus'),
      s('store', 'a store', 'uma loja'),
      s('seat', 'an empty seat', 'um assento vazio'),
    ],
    [
      s('nearby', 'nearby', 'por perto'),
      s('corner', 'on the corner', 'na esquina'),
      s('upstairs', 'upstairs', 'no andar de cima'),
      s('outside', 'outside', 'do lado de fora'),
      s('building', 'in this building', 'neste prédio'),
      s('station', 'at the station', 'na estação'),
      s('street', 'across the street', 'do outro lado da rua'),
      s('end_hall', 'at the end of the hall', 'no fim do corredor'),
    ],
  ),
  frame(
    'v3.there_are.plural', 'A1', 'existence',
    'There are {{a}} {{b}}.', 'Tem {{a}} {{b}}.',
    [
      s('restaurants', 'several restaurants', 'vários restaurantes'),
      s('people', 'a lot of people', 'muitas pessoas'),
      s('chairs', 'some chairs', 'algumas cadeiras'),
      s('shops', 'two shops', 'duas lojas'),
      s('questions', 'a few questions', 'algumas perguntas'),
      s('rooms', 'three rooms', 'três quartos'),
      s('buses', 'several buses', 'vários ônibus'),
      s('options', 'some good options', 'algumas boas opções'),
    ],
    [
      s('nearby', 'nearby', 'por perto'),
      s('corner', 'on this street', 'nesta rua'),
      s('upstairs', 'upstairs', 'no andar de cima'),
      s('outside', 'outside', 'do lado de fora'),
      s('building', 'in this building', 'neste prédio'),
      s('station', 'at the station', 'na estação'),
      s('center', 'downtown', 'no centro'),
      s('area', 'in this area', 'nesta área'),
    ],
  ),
  frame(
    'v3.location.on', 'A1', 'prepositions',
    '{{a}} is {{b}}.', '{{a}} está {{b}}.',
    [
      s('phone', 'The phone', 'O celular'),
      s('key', 'The key', 'A chave'),
      s('book', 'The book', 'O livro'),
      s('wallet', 'The wallet', 'A carteira'),
      s('cup', 'The cup', 'A xícara'),
      s('bag', 'The bag', 'A bolsa'),
      s('ticket', 'The ticket', 'O ingresso'),
      s('remote', 'The remote', 'O controle remoto'),
    ],
    [
      s('table', 'on the table', 'na mesa'),
      s('desk', 'on the desk', 'na escrivaninha'),
      s('counter', 'on the counter', 'no balcão'),
      s('chair', 'on the chair', 'na cadeira'),
      s('shelf', 'on the shelf', 'na prateleira'),
      s('bed', 'on the bed', 'na cama'),
      s('sofa', 'on the sofa', 'no sofá'),
      s('floor', 'on the floor', 'no chão'),
    ],
  ),
  frame(
    'v3.location.in', 'A1', 'prepositions',
    '{{a}} is {{b}}.', '{{a}} está {{b}}.',
    [
      s('phone', 'The phone', 'O celular'),
      s('key', 'The key', 'A chave'),
      s('book', 'The book', 'O livro'),
      s('wallet', 'The wallet', 'A carteira'),
      s('cup', 'The cup', 'A xícara'),
      s('ticket', 'The ticket', 'O ingresso'),
      s('passport', 'The passport', 'O passaporte'),
      s('charger', 'The charger', 'O carregador'),
    ],
    [
      s('bag', 'in the bag', 'na bolsa'),
      s('drawer', 'in the drawer', 'na gaveta'),
      s('car', 'in the car', 'no carro'),
      s('box', 'in the box', 'na caixa'),
      s('room', 'in the room', 'no quarto'),
      s('kitchen', 'in the kitchen', 'na cozinha'),
      s('office', 'in the office', 'no escritório'),
      s('pocket', 'in my pocket', 'no meu bolso'),
    ],
  ),
  frame(
    'v3.location.next_to', 'A1-A2', 'prepositions',
    '{{a}} is next to {{b}}.', '{{a}} fica ao lado {{b}}.',
    [
      s('cafe', 'The café', 'O café'),
      s('hotel', 'The hotel', 'O hotel'),
      s('bank', 'The bank', 'O banco'),
      s('pharmacy', 'The pharmacy', 'A farmácia'),
      s('station', 'The station', 'A estação'),
      s('office', 'The office', 'O escritório'),
      s('restaurant', 'The restaurant', 'O restaurante'),
      s('market', 'The market', 'O mercado'),
    ],
    [
      s('park', 'to the park', 'do parque'),
      s('museum', 'to the museum', 'do museu'),
      s('hospital', 'to the hospital', 'do hospital'),
      s('library', 'to the library', 'da biblioteca'),
      s('school', 'to the school', 'da escola'),
      s('mall', 'to the mall', 'do shopping'),
      s('cinema', 'to the cinema', 'do cinema'),
      s('bridge', 'to the bridge', 'da ponte'),
    ],
  ),
  frame(
    'v3.directions.how_to_get', 'A2', 'directions',
    'How do I get to {{a}} from {{b}}?', 'Como eu chego {{a}} saindo {{b}}?',
    [
      s('station', 'the station', 'à estação'),
      s('airport', 'the airport', 'ao aeroporto'),
      s('museum', 'the museum', 'ao museu'),
      s('hotel', 'the hotel', 'ao hotel'),
      s('hospital', 'the hospital', 'ao hospital'),
      s('center', 'the city center', 'ao centro'),
      s('mall', 'the mall', 'ao shopping'),
      s('university', 'the university', 'à universidade'),
    ],
    [
      s('here', 'here', 'daqui'),
      s('hotel', 'the hotel', 'do hotel'),
      s('station', 'the bus station', 'da rodoviária'),
      s('airport', 'the airport', 'do aeroporto'),
      s('center', 'downtown', 'do centro'),
      s('office', 'the office', 'do escritório'),
      s('park', 'the park', 'do parque'),
      s('museum', 'the museum', 'do museu'),
    ],
  ),
  frame(
    'v3.polite_request.could_you', 'A2', 'requests',
    'Could you {{a}} {{b}}?', 'Você poderia {{a}} {{b}}?',
    [
      s('help', 'help me', 'me ajudar'),
      s('repeat', 'repeat that', 'repetir isso'),
      s('open', 'open the door', 'abrir a porta'),
      s('send', 'send the file', 'enviar o arquivo'),
      s('check', 'check this', 'verificar isto'),
      s('call', 'call me', 'me ligar'),
      s('wait', 'wait here', 'esperar aqui'),
      s('write', 'write it down', 'anotar isso'),
    ],
    GENERIC_REQUEST_CONTEXTS,
  ),
  frame(
    'v3.would_like.request', 'A2', 'requests',
    'I would like {{a}} {{b}}.', 'Eu gostaria de {{a}} {{b}}.',
    [
      s('coffee', 'a coffee', 'um café'),
      s('water', 'a glass of water', 'um copo de água'),
      s('table', 'a table for two', 'uma mesa para dois'),
      s('sandwich', 'the chicken sandwich', 'o sanduíche de frango'),
      s('receipt', 'a receipt', 'um recibo'),
      s('help', 'some help', 'alguma ajuda'),
      s('towel', 'another towel', 'outra toalha'),
      s('checkout', 'a late checkout', 'um check-out tardio'),
    ],
    [
      s('please', 'please', 'por favor'),
      s('if_possible', 'if possible', 'se possível'),
      s('for_me', 'for me', 'para mim'),
      s('now', 'now', 'agora'),
      s('morning', 'this morning', 'hoje de manhã'),
      s('tonight', 'for tonight', 'para hoje à noite'),
      s('noon', 'before noon', 'antes do meio-dia'),
      s('soon', 'as soon as possible', 'assim que possível'),
    ],
  ),
  frame(
    'v3.offer.would_you_like', 'A2', 'offers',
    'Would you like {{a}} {{b}}?', 'Você gostaria de {{a}} {{b}}?',
    [
      s('water', 'some water', 'um pouco de água'),
      s('coffee', 'some coffee', 'um pouco de café'),
      s('seat', 'a seat', 'um lugar para sentar'),
      s('copy', 'a copy', 'uma cópia'),
      s('help', 'some help', 'alguma ajuda'),
      s('bag', 'a bag', 'uma sacola'),
      s('receipt', 'a receipt', 'um recibo'),
      s('time', 'more time', 'mais tempo'),
    ],
    [
      s('now', 'now', 'agora'),
      s('first', 'first', 'primeiro'),
      s('before_leave', 'before we leave', 'antes de irmos embora'),
      s('for_later', 'for later', 'para mais tarde'),
      s('with_that', 'with that', 'com isso'),
      s('while_wait', 'while you wait', 'enquanto você espera'),
      s('morning', 'this morning', 'hoje de manhã'),
      s('trip', 'for the trip', 'para a viagem'),
    ],
  ),
  frame(
    'v3.quantity.how_many', 'A1-A2', 'quantity',
    'How many {{a}} do you need {{b}}?', '{{a}} você precisa {{b}}?',
    [
      s('tickets', 'tickets', 'De quantos ingressos'),
      s('chairs', 'chairs', 'De quantas cadeiras'),
      s('rooms', 'rooms', 'De quantos quartos'),
      s('bottles', 'bottles', 'De quantas garrafas'),
      s('copies', 'copies', 'De quantas cópias'),
      s('days', 'days', 'De quantos dias'),
      s('bags', 'bags', 'De quantas sacolas'),
      s('boxes', 'boxes', 'De quantas caixas'),
    ],
    [
      s('today', 'today', 'hoje'),
      s('trip', 'for the trip', 'para a viagem'),
      s('meeting', 'for the meeting', 'para a reunião'),
      s('week', 'this week', 'esta semana'),
      s('party', 'for the party', 'para a festa'),
      s('project', 'for the project', 'para o projeto'),
      s('order', 'for the order', 'para o pedido'),
      s('tomorrow', 'for tomorrow', 'para amanhã'),
    ],
  ),
  frame(
    'v3.quantity.how_much', 'A1-A2', 'quantity',
    'How much {{a}} do we need {{b}}?', '{{a}} nós precisamos {{b}}?',
    [
      s('water', 'water', 'De quanta água'),
      s('coffee', 'coffee', 'De quanto café'),
      s('rice', 'rice', 'De quanto arroz'),
      s('time', 'time', 'De quanto tempo'),
      s('money', 'money', 'De quanto dinheiro'),
      s('milk', 'milk', 'De quanto leite'),
      s('bread', 'bread', 'De quanto pão'),
      s('space', 'space', 'De quanto espaço'),
    ],
    [
      s('today', 'today', 'hoje'),
      s('trip', 'for the trip', 'para a viagem'),
      s('meeting', 'for the meeting', 'para a reunião'),
      s('week', 'this week', 'esta semana'),
      s('party', 'for the party', 'para a festa'),
      s('project', 'for the project', 'para o projeto'),
      s('order', 'for the order', 'para o pedido'),
      s('tomorrow', 'for tomorrow', 'para amanhã'),
    ],
  ),
  frame(
    'v3.comparative.common', 'A2', 'comparison',
    '{{a}} is {{b}}.', '{{a}} é {{b}}.',
    [
      s('option', 'This option', 'Esta opção'),
      s('route', 'The first route', 'A primeira rota'),
      s('hotel', 'This hotel', 'Este hotel'),
      s('phone', 'The new phone', 'O celular novo'),
      s('room', 'This room', 'Este quarto'),
      s('plan', 'The new plan', 'O plano novo'),
      s('train', 'The train', 'O trem'),
      s('service', 'This service', 'Este serviço'),
    ],
    [
      s('cheaper', 'cheaper than the other one', 'mais barato que o outro'),
      s('faster', 'faster than the old one', 'mais rápido que o antigo'),
      s('better', 'better than the first one', 'melhor que o primeiro'),
      s('easier', 'easier than I expected', 'mais fácil do que eu esperava'),
      s('safer', 'safer than the alternative', 'mais seguro que a alternativa'),
      s('closer', 'closer than the other place', 'mais perto que o outro lugar'),
      s('quieter', 'quieter than the last one', 'mais silencioso que o último'),
      s('simpler', 'simpler than the original', 'mais simples que o original'),
    ],
  ),
  frame(
    'v3.because.cannot_reason', 'A2', 'connectors',
    'I cannot {{a}} because {{b}}.', 'Eu não posso {{a}} porque {{b}}.',
    [
      s('come', 'come tonight', 'ir hoje à noite'),
      s('stay', 'stay longer', 'ficar mais tempo'),
      s('answer', 'answer now', 'responder agora'),
      s('drive', 'drive today', 'dirigir hoje'),
      s('join', 'join the meeting', 'participar da reunião'),
      s('finish', 'finish now', 'terminar agora'),
      s('talk', 'talk right now', 'falar agora'),
      s('go_out', 'go out', 'sair'),
    ],
    [
      s('working', 'I am working late', 'vou trabalhar até tarde'),
      s('sick', 'I am sick', 'estou doente'),
      s('car_shop', 'my car is in the shop', 'meu carro está na oficina'),
      s('no_internet', 'I have no internet', 'estou sem internet'),
      s('delivery', 'I am waiting for a delivery', 'estou esperando uma entrega'),
      s('appointment', 'I have an appointment', 'tenho um compromisso'),
      s('kids', 'I am taking care of the kids', 'estou cuidando das crianças'),
      s('weather', 'the weather is bad', 'o tempo está ruim'),
    ],
  ),
  frame(
    'v3.if.first_conditional', 'A2-B1', 'conditionals',
    'If {{a}}, I will {{b}}.', 'Se {{a}}, eu vou {{b}}.',
    [
      s('rains', 'it rains', 'chover'),
      s('finish_early', 'I finish early', 'eu terminar cedo'),
      s('you_call', 'you call me', 'você me ligar'),
      s('traffic', 'traffic is bad', 'o trânsito estiver ruim'),
      s('time', 'I have time', 'eu tiver tempo'),
      s('meeting', 'the meeting ends early', 'a reunião terminar cedo'),
      s('store', 'the store is open', 'a loja estiver aberta'),
      s('weather', 'the weather improves', 'o tempo melhorar'),
    ],
    [
      s('change_plan', 'change the plan', 'mudar o plano'),
      s('let_know', 'let you know', 'avisar você'),
      s('leave_later', 'leave a little later', 'sair um pouco mais tarde'),
      s('check_again', 'check again', 'verificar de novo'),
      s('make_plan', 'make another plan', 'fazer outro plano'),
      s('send_message', 'send you a message', 'mandar uma mensagem para você'),
      s('decide_then', 'decide then', 'decidir na hora'),
      s('take_care', 'take care of it', 'resolver isso'),
    ],
  ),
  frame(
    'v3.when.future_sequence', 'A2', 'time_clauses',
    'When {{a}}, I will {{b}}.', 'Quando {{a}}, eu vou {{b}}.',
    [
      s('arrive_home', 'I get home', 'eu chegar em casa'),
      s('meeting_ends', 'the meeting ends', 'a reunião terminar'),
      s('you_arrive', 'you arrive', 'você chegar'),
      s('store_opens', 'the store opens', 'a loja abrir'),
      s('finish_work', 'I finish work', 'eu terminar o trabalho'),
      s('train_arrives', 'the train arrives', 'o trem chegar'),
      s('food_ready', 'the food is ready', 'a comida estiver pronta'),
      s('rain_stops', 'the rain stops', 'a chuva parar'),
    ],
    [
      s('call', 'call you', 'ligar para você'),
      s('send', 'send the message', 'enviar a mensagem'),
      s('leave', 'leave', 'sair'),
      s('eat', 'eat', 'comer'),
      s('check', 'check the schedule', 'verificar o horário'),
      s('rest', 'rest for a while', 'descansar um pouco'),
      s('go', 'go there', 'ir para lá'),
      s('decide', 'decide what to do', 'decidir o que fazer'),
    ],
  ),
  frame(
    'v3.before.sequence', 'A2', 'time_clauses',
    'I {{a}} before I {{b}}.', 'Eu {{a}} antes de {{b}}.',
    [
      s('check_email', 'check my email', 'verifico meu e-mail'),
      s('eat_breakfast', 'eat breakfast', 'tomo café da manhã'),
      s('pack_bag', 'pack my bag', 'arrumo minha bolsa'),
      s('lock_door', 'lock the door', 'tranco a porta'),
      s('make_coffee', 'make coffee', 'faço café'),
      s('shower', 'take a shower', 'tomo banho'),
      s('call_client', 'call the client', 'ligo para o cliente'),
      s('review_notes', 'review my notes', 'reviso minhas anotações'),
    ],
    [
      s('leave_home', 'leave home', 'sair de casa'),
      s('start_work', 'start work', 'começar a trabalhar'),
      s('go_bed', 'go to bed', 'ir dormir'),
      s('join_meeting', 'join the meeting', 'entrar na reunião'),
      s('drive', 'drive', 'dirigir'),
      s('travel', 'travel', 'viajar'),
      s('cook', 'cook dinner', 'preparar o jantar'),
      s('send_report', 'send the report', 'enviar o relatório'),
    ],
  ),
  frame(
    'v3.used_to.past_habit', 'B1', 'used_to',
    'I used to {{a}} {{b}}.', 'Eu costumava {{a}} {{b}}.',
    [
      s('walk_school', 'walk to school', 'ir a pé para a escola'),
      s('play_soccer', 'play soccer', 'jogar futebol'),
      s('live_center', 'live downtown', 'morar no centro'),
      s('work_nights', 'work nights', 'trabalhar à noite'),
      s('visit_grandparents', 'visit my grandparents', 'visitar meus avós'),
      s('read_more', 'read more', 'ler mais'),
      s('take_bus', 'take the bus', 'pegar o ônibus'),
      s('cook_daily', 'cook every day', 'cozinhar todos os dias'),
    ],
    [
      s('child', 'when I was a child', 'quando eu era criança'),
      s('student', 'when I was a student', 'quando eu era estudante'),
      s('old_job', 'at my old job', 'no meu trabalho antigo'),
      s('old_city', 'when I lived in my old city', 'quando eu morava na minha antiga cidade'),
      s('college', 'in college', 'na faculdade'),
      s('younger', 'when I was younger', 'quando eu era mais jovem'),
      s('alone', 'when I lived alone', 'quando eu morava sozinho'),
      s('before_car', 'before I had a car', 'antes de eu ter um carro'),
    ],
  ),
  frame(
    'v3.present_perfect.experience', 'B1', 'present_perfect',
    'I have {{a}} {{b}}.', 'Eu já {{a}} {{b}}.',
    [
      s('visited', 'visited that city', 'visitei essa cidade'),
      s('tried', 'tried that restaurant', 'experimentei esse restaurante'),
      s('seen', 'seen that movie', 'vi esse filme'),
      s('used', 'used this app', 'usei este aplicativo'),
      s('taken', 'taken this train', 'peguei este trem'),
      s('stayed', 'stayed at that hotel', 'fiquei nesse hotel'),
      s('read', 'read that book', 'li esse livro'),
      s('met', 'met that person', 'conheci essa pessoa'),
    ],
    [
      s('before', 'before', 'antes'),
      s('many_times', 'many times', 'muitas vezes'),
      s('few_times', 'a few times', 'algumas vezes'),
      s('recently', 'recently', 'recentemente'),
      s('this_year', 'this year', 'este ano'),
      s('more_once', 'more than once', 'mais de uma vez'),
      s('family', 'with my family', 'com minha família'),
      s('vacation', 'on vacation', 'nas férias'),
    ],
  ),
  frame(
    'v3.present_perfect.duration', 'B1', 'present_perfect',
    'I have {{a}} for {{b}}.', 'Eu {{a}} há {{b}}.',
    [
      s('lived_here', 'lived here', 'moro aqui'),
      s('worked_here', 'worked here', 'trabalho aqui'),
      s('known_her', 'known her', 'a conheço'),
      s('had_car', 'had this car', 'tenho este carro'),
      s('used_app', 'used this app', 'uso este aplicativo'),
      s('studied_english', 'studied English', 'estudo inglês'),
      s('waited', 'waited for this', 'espero por isso'),
      s('been_member', 'been a member', 'sou membro'),
    ],
    [
      s('one_year', 'one year', 'um ano'),
      s('two_years', 'two years', 'dois anos'),
      s('few_months', 'a few months', 'alguns meses'),
      s('several_weeks', 'several weeks', 'várias semanas'),
      s('long_time', 'a long time', 'muito tempo'),
      s('six_months', 'six months', 'seis meses'),
      s('three_years', 'three years', 'três anos'),
      s('almost_year', 'almost a year', 'quase um ano'),
    ],
  ),
  frame(
    'v3.present_perfect.ever_question', 'B1', 'questions',
    'Have you ever {{a}} {{b}}?', 'Você já {{a}} {{b}}?',
    [
      s('traveled', 'traveled', 'viajou'),
      s('worked', 'worked', 'trabalhou'),
      s('driven', 'driven', 'dirigiu'),
      s('cooked', 'cooked', 'cozinhou'),
      s('studied', 'studied', 'estudou'),
      s('stayed', 'stayed in a hotel', 'ficou em um hotel'),
      s('spoken', 'spoken English', 'falou inglês'),
      s('taken_train', 'taken a night train', 'pegou um trem noturno'),
    ],
    [
      s('alone', 'alone', 'sozinho'),
      s('friends', 'with friends', 'com amigos'),
      s('work', 'for work', 'a trabalho'),
      s('vacation', 'on vacation', 'nas férias'),
      s('night', 'at night', 'à noite'),
      s('other_city', 'in another city', 'em outra cidade'),
      s('abroad', 'abroad', 'no exterior'),
      s('before', 'before', 'antes'),
    ],
  ),
  frame(
    'v3.prefer.preference', 'A2', 'preferences',
    'I prefer {{a}} to {{b}}.', 'Eu prefiro {{a}} a {{b}}.',
    [
      s('coffee', 'coffee', 'café'),
      s('tea', 'tea', 'chá'),
      s('train', 'the train', 'o trem'),
      s('walking', 'walking', 'caminhar'),
      s('morning', 'the morning', 'a manhã'),
      s('home', 'working from home', 'trabalhar de casa'),
      s('books', 'books', 'livros'),
      s('cooking', 'cooking at home', 'cozinhar em casa'),
    ],
    [
      s('soda', 'soda', 'refrigerante'),
      s('juice', 'juice', 'suco'),
      s('bus', 'the bus', 'o ônibus'),
      s('driving', 'driving', 'dirigir'),
      s('night', 'the evening', 'a noite'),
      s('office', 'working at the office', 'trabalhar no escritório'),
      s('tv', 'watching TV', 'assistir TV'),
      s('eating_out', 'eating out', 'comer fora'),
    ],
  ),
  frame(
    'v3.too_busy_to', 'A2-B1', 'degree',
    'I am too busy to {{a}} {{b}}.', 'Eu estou ocupado demais para {{a}} {{b}}.',
    [
      s('talk', 'talk', 'conversar'),
      s('go', 'go out', 'sair'),
      s('cook', 'cook', 'cozinhar'),
      s('shop', 'go shopping', 'fazer compras'),
      s('travel', 'travel', 'viajar'),
      s('meet', 'meet today', 'me encontrar hoje'),
      s('answer', 'answer everything', 'responder tudo'),
      s('finish', 'finish another task', 'terminar outra tarefa'),
    ],
    [
      s('now', 'right now', 'agora'),
      s('today', 'today', 'hoje'),
      s('morning', 'this morning', 'hoje de manhã'),
      s('afternoon', 'this afternoon', 'hoje à tarde'),
      s('before_lunch', 'before lunch', 'antes do almoço'),
      s('before_meeting', 'before the meeting', 'antes da reunião'),
      s('tonight', 'tonight', 'hoje à noite'),
      s('week', 'this week', 'esta semana'),
    ],
  ),
  frame(
    'v3.not_enough_time', 'A2-B1', 'degree',
    'We do not have enough time to {{a}} {{b}}.', 'Nós não temos tempo suficiente para {{a}} {{b}}.',
    [
      s('finish', 'finish everything', 'terminar tudo'),
      s('wait', 'wait much longer', 'esperar muito mais'),
      s('visit', 'visit every place', 'visitar todos os lugares'),
      s('check', 'check every detail', 'verificar todos os detalhes'),
      s('cook', 'cook a full meal', 'preparar uma refeição completa'),
      s('drive', 'drive there', 'dirigir até lá'),
      s('change', 'change the whole plan', 'mudar todo o plano'),
      s('discuss', 'discuss every point', 'discutir todos os pontos'),
    ],
    [
      s('today', 'today', 'hoje'),
      s('now', 'right now', 'agora'),
      s('morning', 'this morning', 'hoje de manhã'),
      s('before_leave', 'before we leave', 'antes de irmos embora'),
      s('meeting', 'before the meeting', 'antes da reunião'),
      s('deadline', 'before the deadline', 'antes do prazo'),
      s('tonight', 'tonight', 'hoje à noite'),
      s('trip', 'during this trip', 'durante esta viagem'),
    ],
  ),
  frame(
    'v3.but.simple_contrast', 'A1-A2', 'connectors',
    '{{a}}, but {{b}}.', '{{a}}, mas {{b}}.',
    [
      s('tired', 'I am tired', 'eu estou cansado'),
      s('busy', 'I am busy', 'eu estou ocupado'),
      s('small', 'The room is small', 'o quarto é pequeno'),
      s('old', 'The car is old', 'o carro é antigo'),
      s('far', 'The hotel is far', 'o hotel é longe'),
      s('cold', 'It is cold', 'está frio'),
      s('late', 'It is late', 'está tarde'),
      s('expensive', 'The ticket is expensive', 'o ingresso é caro'),
    ],
    [
      s('happy', 'I am happy', 'eu estou feliz'),
      s('finish', 'I can finish today', 'eu posso terminar hoje'),
      s('comfortable', 'it is comfortable', 'ele é confortável'),
      s('works', 'it works well', 'ele funciona bem'),
      s('good', 'it is very good', 'ele é muito bom'),
      s('sunny', 'it is sunny', 'está ensolarado'),
      s('stay', 'we can stay a little longer', 'podemos ficar mais um pouco'),
      s('worth', 'it is worth it', 'vale a pena'),
    ],
  ),
  frame(
    'v3.and.sequence', 'A1', 'connectors',
    'I {{a}} and then I {{b}}.', 'Eu {{a}} e depois {{b}}.',
    [
      s('wake', 'wake up', 'acordo'),
      s('shower', 'take a shower', 'tomo banho'),
      s('breakfast', 'eat breakfast', 'tomo café da manhã'),
      s('email', 'check my email', 'vejo meu e-mail'),
      s('work', 'finish work', 'termino o trabalho'),
      s('shop', 'buy groceries', 'faço compras'),
      s('cook', 'cook dinner', 'preparo o jantar'),
      s('pack', 'pack my bag', 'arrumo minha bolsa'),
    ],
    [
      s('coffee', 'make coffee', 'faço café'),
      s('leave', 'leave home', 'saio de casa'),
      s('start', 'start work', 'começo a trabalhar'),
      s('call', 'call my family', 'ligo para minha família'),
      s('rest', 'rest for a while', 'descanso um pouco'),
      s('eat', 'eat dinner', 'janto'),
      s('read', 'read for a while', 'leio um pouco'),
      s('sleep', 'go to bed', 'vou dormir'),
    ],
  ),
  frame(
    'v3.or.choice', 'A1-A2', 'connectors',
    'Do you want to {{a}} or {{b}}?', 'Você quer {{a}} ou {{b}}?',
    [
      s('eat_here', 'eat here', 'comer aqui'),
      s('walk', 'walk', 'caminhar'),
      s('leave_now', 'leave now', 'sair agora'),
      s('call', 'call them', 'ligar para eles'),
      s('pay_cash', 'pay in cash', 'pagar em dinheiro'),
      s('stay_home', 'stay home', 'ficar em casa'),
      s('take_train', 'take the train', 'pegar o trem'),
      s('start_now', 'start now', 'começar agora'),
    ],
    [
      s('take_away', 'take it to go', 'levar para viagem'),
      s('bus', 'take the bus', 'pegar o ônibus'),
      s('wait', 'wait a little', 'esperar um pouco'),
      s('message', 'send a message', 'mandar uma mensagem'),
      s('card', 'pay by card', 'pagar com cartão'),
      s('go_out', 'go out', 'sair'),
      s('drive', 'drive', 'ir de carro'),
      s('later', 'do it later', 'fazer isso mais tarde'),
    ],
  ),
  frame(
    'v3.still.continuity_general', 'A2', 'aspect_adverb',
    '{{a}} still {{b}}.', '{{a}} ainda {{b}}.',
    [
      s('they', 'They', 'Eles'),
      s('parents', 'My parents', 'Meus pais'),
      s('friends', 'My friends', 'Meus amigos'),
      s('neighbors', 'Our neighbors', 'Nossos vizinhos'),
      s('students', 'The students', 'Os alunos'),
      s('managers', 'The managers', 'Os gerentes'),
      s('cousins', 'My cousins', 'Meus primos'),
      s('team', 'The team members', 'Os membros da equipe'),
    ],
    [
      s('live_here', 'live here', 'moram aqui'),
      s('work_here', 'work here', 'trabalham aqui'),
      s('use_app', 'use this app', 'usam este aplicativo'),
      s('need_time', 'need more time', 'precisam de mais tempo'),
      s('talk_week', 'talk every week', 'conversam toda semana'),
      s('wait_answer', 'wait for an answer', 'esperam uma resposta'),
      s('study_english', 'study English', 'estudam inglês'),
      s('remember', 'remember that day', 'lembram daquele dia'),
    ],
  ),
  frame(
    'v3.already.completed', 'A2-B1', 'aspect_adverb',
    'I have already {{a}} {{b}}.', 'Eu já {{a}} {{b}}.',
    [
      s('finished', 'finished the report', 'terminei o relatório'),
      s('sent', 'sent the email', 'enviei o e-mail'),
      s('called', 'called the client', 'liguei para o cliente'),
      s('paid', 'paid the bill', 'paguei a conta'),
      s('booked', 'booked the hotel', 'reservei o hotel'),
      s('checked', 'checked the address', 'verifiquei o endereço'),
      s('bought', 'bought the tickets', 'comprei os ingressos'),
      s('read', 'read the message', 'li a mensagem'),
    ],
    [
      s('today', 'today', 'hoje'),
      s('morning', 'this morning', 'hoje de manhã'),
      s('week', 'this week', 'esta semana'),
      s('before_meeting', 'before the meeting', 'antes da reunião'),
      s('for_trip', 'for the trip', 'para a viagem'),
      s('online', 'online', 'pela internet'),
      s('at_work', 'at work', 'no trabalho'),
      s('for_us', 'for us', 'para nós'),
    ],
  ),
  frame(
    'v3.yet.question', 'A2-B1', 'aspect_adverb',
    '{{a}} {{b}}', '{{a}} {{b}}',
    [
      s('finished', 'Have you finished the report yet?', 'Você já terminou o relatório?'),
      s('called', 'Have you called them yet?', 'Você já ligou para eles?'),
      s('paid', 'Have you paid the bill yet?', 'Você já pagou a conta?'),
      s('decided', 'Have you decided yet?', 'Você já decidiu?'),
      s('eaten', 'Have you eaten yet?', 'Você já comeu?'),
      s('arrived', 'Have they arrived yet?', 'Eles já chegaram?'),
      s('booked', 'Have you booked the hotel yet?', 'Você já reservou o hotel?'),
      s('checked', 'Have you checked the schedule yet?', 'Você já verificou o horário?'),
    ],
    [
      s('need_know', 'I need to know.', 'Eu preciso saber.'),
      s('can_wait', 'I can wait a little.', 'Eu posso esperar um pouco.'),
      s('no_rush', 'There is no rush.', 'Não há pressa.'),
      s('tell_me', 'Please tell me when you can.', 'Por favor, me avise quando puder.'),
      s('checking', 'I am just checking.', 'Só estou conferindo.'),
      s('plan_after', 'We can plan after that.', 'Podemos planejar depois disso.'),
      s('update_me', 'Send me an update when you can.', 'Me mande uma atualização quando puder.'),
      s('later_ok', 'Later is fine too.', 'Mais tarde também está bom.'),
    ],
  ),
  frame(
    'v3.first_conditional.unless', 'B1', 'conditionals',
    'Unless {{a}}, we will {{b}}.', 'A menos que {{a}}, nós vamos {{b}}.',
    [
      s('rains', 'it rains', 'chova'),
      s('traffic', 'traffic gets worse', 'o trânsito piore'),
      s('client_changes', 'the client changes the deadline', 'o cliente mude o prazo'),
      s('train_delay', 'the train is delayed', 'o trem atrase'),
      s('weather', 'the weather changes', 'o tempo mude'),
      s('someone_calls', 'someone calls', 'alguém ligue'),
      s('store_closes', 'the store closes early', 'a loja feche cedo'),
      s('meeting_runs', 'the meeting runs late', 'a reunião termine tarde'),
    ],
    [
      s('go_outside', 'eat outside', 'comer do lado de fora'),
      s('arrive_six', 'arrive before six', 'chegar antes das seis'),
      s('finish_today', 'finish today', 'terminar hoje'),
      s('leave_time', 'leave on time', 'sair no horário'),
      s('keep_plan', 'keep the same plan', 'manter o mesmo plano'),
      s('meet_lobby', 'meet in the lobby', 'nos encontrar no saguão'),
      s('buy_today', 'buy it today', 'comprar isso hoje'),
      s('start_morning', 'start in the morning', 'começar de manhã'),
    ],
  ),
])

export const COMBINATORIAL_V3_EXPECTED_FRAME_COUNT = 48
export const COMBINATORIAL_V3_MINIMUM_REALIZATIONS = 2000
